export { default as Sidebar } from "./Sidebar"
export { default as Content } from "./Content"
export { default as MonkeyTypeContent } from "./monkeyType/MonkeyType"
export { default as WakatimeContent } from "./wakatime/Wakatime"
export { default as GithubContent } from "./github/Github"
